Add: smoketest for openvas-nasl-lint
greenbone/openvas-scanner pull request #1125
Opened 2022-06-09 20:10 UTC by Kraemii

**What**:
A smoke-test to verify the functionality of openvas-nasl-lint

**Why**:

**How**:
In the current state the smoketest can only be triggered manually, but a github-actions implementation is already ongoing.
To start the smoketest just go into the `smoketest_lint` folder and run `make all`

**Checklist**:

- [ ] Tests
- [ ] PR merge commit message adjusted

2022-06-14 10:55 UTC, nichtsfrei commented on smoketest_lint/cmd/main.go
> +	openvasDir := flag.String("openvasDir", "", "location of the openvas-nasl-lint executable, has to be absolute or relative to test files directory")
Instead of just adding the root dir of a executable I would rather use executable or e and set the default to openvas-nasl-lint?

2022-06-14 11:25 UTC, nichtsfrei requested changes

2022-06-14 11:25 UTC, nichtsfrei commented on smoketest_lint/cmd/main.go
> +	openvasDir := flag.String("openvasDir", "", "location of the openvas-nasl-lint executable, has to be absolute or relative to test files directory")
Also a little bit of output when running would be nice.

2022-06-14 11:31 UTC, nichtsfrei requested changes

2022-06-14 13:29 UTC, Kraemii commented on smoketest_lint/test/testfile.go
> +	if !strings.Contains(err.Error(), "exit status") {
The comment is a bit irritating as I forgot to adjust it. I wantet to filter for Errors which are not ExitErrors, as these will occur when checking files which contains openvas-nasl-lint errors. Now it should be much more clear, also used `errors.As`, as `errors.Is` checks for equality of two errors.

2022-06-15 07:05 UTC, nichtsfrei approved these changes

2022-06-15 10:13 UTC, merged