Change: Improve stop_denial. Test the host if still alive with boreas
greenbone/openvas-scanner pull request #1345
Opened 2023-02-22 07:33 UTC by jjnicola

**What**:
Improve stop_denial. Test the host if still alive with boreas

**Why**:
Some plugins produce the host scan to finish earlier because false positive.

**How**:

**Checklist**:

- [ ] Tests
- [x] PR merge commit message adjusted

2023-02-22 08:25 UTC, nichtsfrei commented on nasl/nasl_misc_funcs.c
> +  if (check_host_still_alive (kb, plug_current_vhost ()))
mhm, if boreas is either disabled or has an error isn't it better to follow the assumption that it is dead?

2023-02-23 11:46 UTC, nichtsfrei submitted a review, later dismissed

2023-02-28 07:20 UTC, ArnoStiefvater requested changes

2023-02-28 07:20 UTC, ArnoStiefvater commented on misc/heartbeat.c
> +/* Portions Copyright (C) 2009-2022 Greenbone Networks GmbH
License header is wrong, same for the .h file.

2023-02-28 08:40 UTC, ArnoStiefvater approved these changes

2023-03-01 08:58 UTC, Kraemii approved these changes

2023-03-01 08:58 UTC, merged