Fix: override an existing scan only if it is on Stored status
greenbone/openvas-scanner pull request #1460
Opened 2023-07-26 09:34 UTC by jjnicola

**What**:
Fix: override an existing scan only if it is on Stored status
Jira: SC-893

**Why**:
This patch solves an issue in which a running scan could be overriden if a new scan is post/stored with the same scan ID, producing a reset of the running scan status and results lost

**How**:

**Checklist**:

- [ ] Tests
- [ ] PR merge commit message adjusted

2023-08-04 09:47 UTC, Kraemii commented
IMO a scan should never be able to be overwritten, but always deleted first. In case a stored scan can be overwritten, there is always the chance of deleting data, that is still needed and can also lead to clashes in a multi user scenario, as the user has the chance to set an own scan ID. When we enforce the deletion first it is also more explicit.

2023-08-15 15:06 UTC, nichtsfrei requested changes

2023-08-15 15:06 UTC, nichtsfrei commented on rust/models/src/status.rs
> +    pub fn is_stored(&self) -> bool {
why introducing this method? The name of the enum is already Stored.

2023-08-16 10:46 UTC, Kraemii approved these changes

2023-08-16 10:58 UTC, nichtsfrei approved these changes

2023-08-16 10:58 UTC, merged