Rename advisory option
greenbone/openvas-scanner pull request #1539
Opened 2023-12-12 09:05 UTC by Kraemii

**What**:

**Why**:

**How**:

**Checklist**:

- [ ] Tests
- [ ] PR merge commit message adjusted

2023-12-14 07:42 UTC, jjnicola requested changes

2023-12-14 07:42 UTC, jjnicola commented on rust/openvasd/README.md
> +advisory_path = "/var/lib/notus/products/"
```suggestion
products_path = "/var/lib/notus/products/"
```

2023-12-14 07:42 UTC, jjnicola commented on rust/notus/src/loader/mod.rs
>  /// Trait for and AdvisoryLoader
```suggestion
/// Trait for an AdvisoryLoader
```

2023-12-14 07:42 UTC, jjnicola commented on rust/notus/src/loader/mod.rs
>  /// Trait for and AdvisoryLoader
We are loading notus products. Shouldn't be renamed to ProductLoader ?

2023-12-14 07:42 UTC, jjnicola commented on rust/notus/src/loader/mod.rs
> +    fn load_package_advisories(&self, os: &str) -> Result<(Product, FeedStamp), Error>;
Shoulldn't be 
```suggestion
    fn load_package_products(&self, os: &str) -> Result<(Product, FeedStamp), Error>;
```

2023-12-14 07:42 UTC, jjnicola commented on rust/notus/src/loader/hashsum.rs
> +        <HashsumAdvisoryLoader<R, L> as self::SignatureChecker>::signature_check(&path)
```suggestion
        <HashsumProductLoader<R, L> as self::SignatureChecker>::signature_check(&path)
```

2023-12-18 07:10 UTC, jjnicola approved these changes

2023-12-18 07:13 UTC, jjnicola requested changes

2023-12-18 07:13 UTC, jjnicola commented on rust/notus/src/notus.rs
> +/// automatically updates the cache, when the acording file changes.
rs-typo CI test fails because of this 
```suggestion
/// automatically updates the cache, when the according file changes.
```

2023-12-18 08:07 UTC, jjnicola submitted a review, later dismissed

2023-12-18 09:05 UTC, jjnicola approved these changes

2023-12-18 10:28 UTC, nichtsfrei approved these changes

2023-12-18 10:36 UTC, merged