minor fixes
greenbone/openvas-scanner pull request #1613
Opened 2024-04-03 10:51 UTC by nichtsfrei

- **Fix: scannerctl option name and redis-storage dispatcher (#1604)**
- **Fixes typo in control.yml**
- **CI: release tag toml**
- **CI: removes conventional-commits and configured disable-on for labeler**
- **CI: change init.yml to get all information**
- **CI: add debug step**
- **CI: use correct identifier on debug step**
- **CI: set labeler to main**
- **CI: adjust when to run on a PR**
- **CI: change action parameter to configuration-toml**
- **CI: release cannot be dependent on smoketest**
- **CI: utilize github.token to be more flexible**
- **Fix: add redis to the storage options for clap**
- **Add: env REDIS_URL to set redis-url**

2024-04-03 12:28 UTC, jjnicola requested changes
rust/openvasd/README.md needs to be updated with the new storage type and the change from `wrapper-` to `scanner-type`.

2024-04-03 12:49 UTC, nichtsfrei commented
> rust/openvasd/README.md needs to be updated with the new storage type and the change from `wrapper-` to `scanner-type`.

fixed

2024-04-03 13:46 UTC, jjnicola requested changes

2024-04-03 13:46 UTC, jjnicola commented on rust/openvasd/README.md
> +| Wrapper Type             | --scanner-type          |               | scanner                            | type              | WRAPPER_TYPE             | Type of wrapper used to manage scans, curren
```suggestion
| Scanner Type             | --scanner-type          |               | scanner                            | type              | SCANNER_TYPE             | Type of wrapper used to manage scans, currently `openvas` and `ospd` are available                                                                                                  | ospd                          |
```

2024-04-03 13:46 UTC, jjnicola commented on rust/openvasd/README.md
> +| Wrapper Type             | --scanner-type          |               | scanner                            | type              | WRAPPER_TYPE             | Type of wrapper used to manage scans, curren
missing option and fix EnvVar

2024-04-03 13:46 UTC, jjnicola commented on rust/openvasd/README.md
> +| Wrapper Type             | --scanner-type          |               | scanner                            | type              | WRAPPER_TYPE             | Type of wrapper used to manage scans, curren
Also missing  the new `REDIS_URL` environment variable in the options table.

2024-04-08 12:07 UTC, jjnicola approved these changes

2024-04-08 13:44 UTC, merged