Doc: guide for API usage of previous OSP commands
greenbone/openvas-scanner pull request #1614
Opened 2024-04-03 12:21 UTC by jjnicola

**What**:
Document API usage of previous OSP commands
Jira: SC-1006

**Why**:

**How**:

**Checklist**:

- [ ] Tests
- [ ] PR merge commit message adjusted

2024-04-11 09:09 UTC, jjnicola commented on rust/openvasd/doc/osp-cmd-equivalence.md
> +curl --verbose --request GET http://127.0.0.1:3000/vts/1.3.6.1.4.1.25623.1.1.5.2014.322 -H "X-API-KEY: changeme"
As talked, fix will be done within an independent PR. Documentation is kept on this document but it doesn't belong to the API specification.

2024-04-11 09:45 UTC, Kraemii requested changes

2024-04-11 09:45 UTC, Kraemii commented on rust/openvasd/doc/osp-cmd-equivalence.md
> +
```suggestion
```
I would remove the first request example

2024-04-11 09:45 UTC, Kraemii commented on rust/openvasd/doc/osp-cmd-equivalence.md
> +Endpoint: /scans/{scan_id}
Description of scan_id is missing

2024-04-11 09:45 UTC, Kraemii commented on rust/openvasd/doc/osp-cmd-equivalence.md
> +Endpoint: /scans/{scan_id}
Description of scan_id is missing

2024-04-11 13:35 UTC, Kraemii approved these changes

2024-04-17 08:55 UTC, ArnoStiefvater approved these changes

2024-04-17 08:55 UTC, merged