Add: NASL builtin functions for rsa
greenbone/openvas-scanner pull request #1664
Opened 2024-06-21 14:29 UTC by puethenn

Add: NASL builtin functions for rsa

Jira-Ticket: sc-1050

2024-07-08 08:45 UTC, nichtsfrei commented
Possibly last words: I don't think a side channel attack is a high thread considering how those rsa functions are usually used within a larger scan. There I think we can ignore thise audit outcome.

2024-07-08 09:12 UTC, jjnicola requested changes

2024-07-08 09:12 UTC, jjnicola commented on doc/manual/nasl/built-in-functions/cryptographic/rsa_public_decrypt.md
> +## DESCRIPTIONN
Small typo
```suggestion
## DESCRIPTION
```

2024-07-15 15:18 UTC, nichtsfrei submitted a review, later dismissed

2024-09-05 12:07 UTC, Kraemii requested changes
There are few things to do here. If you are not sure, how to implement specific stuff (e.g. the signing) you can look into the corresponding nasl function within the c implementation: [rsa_sign](https://github.com/greenbone/openvas-scanner/blob/main/nasl/nasl_crypto2.c#L1094)

In addition we now have switched to another approach regarding parameters for NASL functions. You can look into https://github.com/greenbone/openvas-scanner/pull/1682 for reference, if you want to use them instead

2024-09-05 12:07 UTC, Kraemii commented on rust/nasl-builtin-cryptographic/src/rsa.rs
> +    let d = get_required_named_data(register, "d")?;
Same for the parameter `pad` as above. In case of padding is disabled, use `rsa::hazmat::rsa_decrypt()` instead

2024-09-05 12:11 UTC, Kraemii commented
A tip: it is useful to regularly call
```
git fetch
git rebase origin/main
```
to stay up to date with the main branch.

2024-10-15 12:31 UTC, closed without merging