Rs network functions
greenbone/openvas-scanner pull request #1693
Opened 2024-08-08 10:33 UTC by Kraemii

**What**:
Implementing the following network functions:
- this_host_name
- get_mtu
- this_host
- islocalhost
- islocalnet
- get_host_ip
- scanner_add_port

for testing I used a minimal NASL script:
```
display(<network_function>);
```
and execute `scannerctl execute script -t <target> test.nasl`

2024-08-15 16:09 UTC, jjnicola requested changes

2024-08-15 16:10 UTC, jjnicola commented on rust/nasl-builtin-network/src/network.rs
> +            if netmask_parts[i] == "0" {
Same for IPv6

2024-08-21 06:50 UTC, Kraemii commented on rust/nasl-builtin-network/src/network.rs
> +            if netmask_parts[i] == "0" {
Should be fixed now

2024-08-21 09:01 UTC, Tehforsch requested changes
Looks good, just had a few comments.

2024-08-21 09:34 UTC, Kraemii commented on rust/nasl-builtin-network/src/lib.rs
> +}
I guess ports are only relevant for the network and raw ip functions, at least regarding NASL

2024-08-21 11:49 UTC, Kraemii commented on rust/nasl-builtin-network/src/network_utils.rs
> +}
I did simplify the unsafe blocks a little bit, to have a better view and wrote a small comment, why this is unsafe

2024-08-21 11:50 UTC, Kraemii commented on rust/nasl-builtin-network/src/network_utils.rs
> +}
Yes, might be a good idea

2024-08-21 16:31 UTC, jjnicola approved these changes

2024-08-22 07:02 UTC, merged