Fix interrupted scans
greenbone/openvas-scanner pull request #832
Opened 2021-08-06 08:05 UTC by jjnicola

SC-177

**What**:
Check if the max running process was reached or even exceed, when waiting for running a new plugin. 

**Why**:
Fix an issue which produced interrupted scan, because a host not being scan 100%

**How**:
Not easy to reproduce. It depends on the system, scan config and mainly on the target system (some plugins must be trigger in a especial order). Good luck.

**Checklist**:

- [ ] Tests
- [x] [CHANGELOG](https://github.com/greenbone/openvas/blob/master/CHANGELOG.md) Entry

2021-08-06 08:48 UTC, bjoernricks commented on src/pluginlaunch.c
> +      g_debug ("There are currently no free slot for running a new plugins, "
Either `a new plugin` or `new plugins`. Maybe
```suggestion
      g_debug ("There are currently no free slot for starting a new plugin, "
```

2021-08-09 05:34 UTC, cfi-gb requested changes

2021-08-09 05:34 UTC, cfi-gb commented on src/attack.c
> +                    "fork() failed for %s. Not free slot to run a plugin.",
```suggestion
                    "fork() failed for %s. No free slot to run a plugin.",
```

2021-08-09 05:34 UTC, cfi-gb commented on src/pluginlaunch.c
> +      g_debug ("There are currently no free slot for starting a new plugin, "
Either `are currently no free slots` or `is currently no free slot` and both probably needs an `available` as well.

2021-08-09 05:34 UTC, cfi-gb commented on src/pluginlaunch.c
> +             "Waitting for free slot for processes.",
```suggestion
             "Waiting for free slot for processes.",
```

2021-08-09 05:34 UTC, cfi-gb commented on src/pluginlaunch.c
> +               "probably because the parallel check is temporally disabled. "
```suggestion
               "probably because the parallel check is temporarily disabled. "
```

2021-08-09 08:51 UTC, ArnoStiefvater commented on src/attack.c
> +      if (pid == ERR_NO_FREE_SLOT)
Update `launch_plugin()` documentation.
Maybe `plugin_launch()` should get a new error parameter so we return pid on success and set and error on error.
This way we do not mix pid value and error value.

2021-08-09 08:51 UTC, ArnoStiefvater commented on src/attack.c
> +                    "fork() failed for %s. No free slot to run a plugin.",
`fork()` was never tried here. ERR_NO_FREE_SLOT is returned long before `create_process()` is called.
Maybe better debug message would be  `Launch failed for %s. No free slot to run a plugin."`

2021-08-09 10:16 UTC, ArnoStiefvater commented on src/attack.c
> +                      g_warning ("Launch failed for %s. No free slot available "
```suggestion
                      g_warning ("Launch failed for %s. No free slot in the internal process table available "
```
Makes it more explicit what is meant with `slot`.

2021-08-09 10:26 UTC, ArnoStiefvater approved these changes

2021-08-09 10:36 UTC, merged