Wait for notus to finish
greenbone/openvas-scanner pull request #917
Opened 2021-10-29 08:46 UTC by Kraemii

**What**:
Openvas waits for notus to finish before finishing scan.
Depends on https://github.com/greenbone/gvm-libs/pull/612
SC-450

**Why**:
In order to guarantee a scan is completely done when openvas sets the finished flag, it waits until notus is finished as well.

**How**:
Use the complete stack to start a full and fast scan. When enabling debug messages in openvas (for main), the status of the notus scan gets logged. (Alternatively a script that just do the package gathering should be enough too). Also in the `openvas.conf` the option `table_driven_lsc = yes` must be set.

**Checklist**:

- [ ] Tests
- [x] PR merge commit message adjusted

2021-11-02 11:52 UTC, nichtsfrei requested changes

2021-11-02 11:52 UTC, nichtsfrei commented on misc/table_driven_lsc.c
> +  // JsonObject *jo;
```suggestion

```

2021-11-02 11:52 UTC, nichtsfrei commented on misc/table_driven_lsc.c
> +  // jo = json_parser_get_root (parser);
```suggestion

```

2021-11-02 11:52 UTC, nichtsfrei commented on misc/table_driven_lsc.c
> + * @brief Get the status of table drifen lsc from json object
```suggestion
 * @brief Get the status of table driven lsc from json object
```

2021-11-02 11:52 UTC, nichtsfrei commented on misc/table_driven_lsc.c
> +get_status_of_table_drifen_lsc_from_json (const char *scan_id,
```suggestion
get_status_of_table_driven_lsc_from_json (const char *scan_id,
```

2021-11-02 11:52 UTC, nichtsfrei commented on misc/table_driven_lsc.h
> +get_status_of_table_drifen_lsc_from_json (const char *, const char *,
```suggestion
get_status_of_table_driven_lsc_from_json (const char *, const char *,
```

2021-11-02 11:52 UTC, nichtsfrei commented on src/attack.c
> +          status = get_status_of_table_drifen_lsc_from_json (
```suggestion
          status = get_status_of_table_driven_lsc_from_json (
```

2021-11-02 11:52 UTC, nichtsfrei commented on src/attack.c
> +              status = get_status_of_table_drifen_lsc_from_json (
```suggestion
              status = get_status_of_table_driven_lsc_from_json (
```

2021-11-11 04:36 UTC, nichtsfrei approved these changes

2021-11-11 06:13 UTC, y0urself approved these changes

2021-11-11 06:13 UTC, merged