Change: extend cert_query() nasl function to get the public key algorithm
greenbone/openvas-scanner pull request #995
Opened 2021-12-08 10:23 UTC by jjnicola

**What**:

**Why**:

**How**:

**Checklist**:

- [ ] Tests
- [ ] PR merge commit message adjusted

2021-12-08 15:28 UTC, cfi-gb requested changes

2021-12-08 15:28 UTC, cfi-gb commented on nasl/nasl_cert.c
> + * - @a algorithm-name: Same as signature-algorithm-name. TODO: Remove it and
Other parameters like `image` are not using the `:`, this one is using it. IMHO the style should stay consistent throughout the whole function description.

2021-12-08 15:28 UTC, cfi-gb commented on nasl/nasl_cert.c
> + * - @a signature-algorithm-name: Return the algorithm name. Get the OID of
```suggestion
 * - @a signature-algorithm-name: Return the algorithm name used to sign the certificate. Get the OID of
```

Not absolutely sure about the text but this should make it a little bit more clear.

2021-12-09 06:50 UTC, cfi-gb commented on nasl/nasl_cert.c
> +
This also looks superfluous and could be dropped as none of the other `else if` parts are using a space after the `{`.

2021-12-09 09:14 UTC, ArnoStiefvater approved these changes

2021-12-09 09:18 UTC, Kraemii approved these changes

2021-12-09 09:18 UTC, merged